### ISSUE TITLE
"error": "Execution of stop timed out after 10.0 s."

### ISSUE THREAD

**Issue by Kagey-cmd** [TheFes/Google-Home-Resume#8]
I'm getting this error every time I attempt to run the resume script.
I've never gotten this to work.
This is a fresh setup, so perhaps it's a configuration issue, but I believe I've followed all of the setup instructions.
https://pastebin.com/zimGM9xr

**Comment by Kagey-cmd** [comment]
Any ideas how I might get this working? Any additional details I can provide?

**Comment by TheFes** [comment]
Sorry, I've never seen this error before, I'll have a look

**Comment by Kagey-cmd** [comment]
I get this every time I use the media_player.media_stop service call:
"Failed to call service media_player.media_stop. CastMediaPlayerEntity.media_stop Failed: Execution of stop timed out after 10.0 s."
Even outside of the Resume Script. It successfully stops media playback, but still gives the error.

**Comment by Kagey-cmd** [comment]
service: media_player.media_stop
target:
  entity_id:
    - media_player.nursery_speaker
data: {}

**Comment by Kagey-cmd** [comment]
Looks to me like it's an issue with my media player integration.

**Comment by TheFes** [comment]
Yes, I think so as well. What kind of speaker is that?

**Comment by Kagey-cmd** [comment]
It's a Google Home Mini. Nothing out of the ordinary.

**Comment by Kagey-cmd** [comment]
#114259

**Comment by Kagey-cmd** [comment]
home-assistant/core#114259

**Comment by TheFes** [comment]
Works fine on mine. Is it a first generation mini?

**Comment by Kagey-cmd** [comment]
Yes, it's a first gen.

**Comment by Kagey-cmd** [comment]
Just got the same error on a Google Home Hub.

**Comment by birdwing** [comment]
> Just got the same error on a Google Home Hub.

Same here. Google Home Hub version 2

**Comment by TheFes** [comment]
As the error also occurs when the stop service call is issued from developer tools > services, this is not an issue with the Google Home Resume script, but in the integration itself. 

Please raise an issue on the cast integration on the Home Assistant core repo

**Comment by Kagey-cmd** [comment]
> As the error also occurs when the stop service call is issued from developer tools > services, this is not an issue with the Google Home Resume script, but in the integration itself.
> 
> Please raise an issue on the cast integration on the Home Assistant core repo

I agree. I've already opened home-assistant/core#114259
I also found home-assistant/core#113918

But Google Home Resume relies heavily on partially broken or deprecated service calls.

**Comment by thegreekgeek** [comment]
Getting the same error here sadly. I just spend a bit trying to troubleshoot the dang thing too!

**Comment by Kagey-cmd** [comment]
@TheFes not that I know of :)

**Comment by Jaykurb** [comment]
> media_player.media_stop

This doesn't work for me. Just can't get to the bottom of it.

**Comment by Kagey-cmd** [comment]
@Jaykurb have you tried replacing _media_stop_ with _media_pause_? I haven't tested this fully, but @thegreekgeek seems to have gotten it working that way.

**Comment by servernotifiche** [comment]
HI all, same problem of Execution of stop timed out after 10.0 s. next days i gonna try with "media_pause.
But I cant find where i have to set the volume (is possible with tts.google_say or tts.speak)?
Thanks

**Comment by servernotifiche** [comment]
HI all, same problem of Execution of stop timed out after 10.0 s. next days i gonna try with "media_pause.
But I cant find where i have to set the volume (is possible with tts.google_say or tts.speak)?
Thanks

**Comment by TheFes** [comment]
@servernotifiche 
Here's an example where volume is set
https://github.com/TheFes/Google-Home-Resume/blob/main/docs%2Fexamples%2Fexamples_google_home_resume.md

**Comment by servernotifiche** [comment]
hi, and thanks for your help.
I tried this in developer tools, but the volume doesn't change


service: script.google_home_resume
data:
  target:
    entity_id: media_player.nest_hub
  action:
    - service: tts.speak
      metadata: {}
      data:
        cache: false
        media_player_entity_id: media_player.nest_hub
        message: messaggio di prova
        language: it
      target:
        entity_id: tts.google_en_com
      extra: 
        volume: 0.80

**Comment by TheFes** [comment]
The script was created way before TTS entities were added. Setting volume will probably not work using the `tts.speak` service call and a TTS entity.

**Comment by servernotifiche** [comment]
uh ok, so Has anyone managed to make it work with tts?

**Comment by TheFes** [comment]
HI!

Sorry it took so long for me to take action. I've been quite busy with some other stuff

I've set up a new branch for a 2024.8 version which should resolve this issue.
Optionall you can still let the players stop before the actions are performed by using the `stop_before_actions: true`
If this is not set the default is `false`, and in that case the stop action will not be used.

However, this version changes a lot more:
* `service:` has been changed to `action` everywhere to reflect the change in Home Assistant 2024.8. This means you also need to have updated to HA 2024.8 for this version to work. 
* The script now also supports `tts.speak` where the media_player target is set under a different key.
* Removed a check which was sometimes blocking resume

Could you please test the version which you can find here.
https://github.com/TheFes/Google-Home-Resume/tree/2024.8.0

**Comment by mmcramos** [comment]
Hi, i am still getting same error when spotify is streaming with this latest script version.

**Comment by TheFes** [comment]
@mmcramos did you add the `stop_before_action` setting? And if so, did you set it to `true` (like I have in my settings).
Please set it to `false` if that's the case (or remove the line completely)

**Comment by mmcramos** [comment]
> @mmcramos did you add the `stop_before_action` setting? And if so, did you set it to `true` (like I have in my settings). Please set it to `false` if that's the case (or remove the line completely)

thanks so much!! it's working now after settting to 'false'

**Comment by TheFes** [comment]
Should be fixed in https://github.com/TheFes/Google-Home-Resume/releases/tag/2024.8.0

**Comment by servernotifiche** [comment]
> @mmcramos did you add the `stop_before_action` setting? And if so, did you set it to `true` (like I have in my settings). Please set it to `false` if that's the case (or remove the line completely)

GREAT! Now is working great!
